// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD912WWGwT5kVT97-_9vBnnNypN2v9u0Bg',
    appId: '1:1061181697738:web:f4157c86cc326d67ec8e33',
    messagingSenderId: '1061181697738',
    projectId: 'worktime-3d2a6',
    authDomain: 'worktime-3d2a6.firebaseapp.com',
    storageBucket: 'worktime-3d2a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYGcM8g5G3_gcMAmeUINH2Vg5SPSyxuY',
    appId: '1:1061181697738:android:d854c4dc4bd7f896ec8e33',
    messagingSenderId: '1061181697738',
    projectId: 'worktime-3d2a6',
    storageBucket: 'worktime-3d2a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtHNJqEm3inbWbWB2wZH25rjnIOww63Ro',
    appId: '1:1061181697738:ios:9cc2cacacc33cea9ec8e33',
    messagingSenderId: '1061181697738',
    projectId: 'worktime-3d2a6',
    storageBucket: 'worktime-3d2a6.firebasestorage.app',
    iosBundleId: 'com.example.worktime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtHNJqEm3inbWbWB2wZH25rjnIOww63Ro',
    appId: '1:1061181697738:ios:9cc2cacacc33cea9ec8e33',
    messagingSenderId: '1061181697738',
    projectId: 'worktime-3d2a6',
    storageBucket: 'worktime-3d2a6.firebasestorage.app',
    iosBundleId: 'com.example.worktime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD912WWGwT5kVT97-_9vBnnNypN2v9u0Bg',
    appId: '1:1061181697738:web:7d6cb6beaf8ad321ec8e33',
    messagingSenderId: '1061181697738',
    projectId: 'worktime-3d2a6',
    authDomain: 'worktime-3d2a6.firebaseapp.com',
    storageBucket: 'worktime-3d2a6.firebasestorage.app',
  );
}
